// Mock data for DYPIU Event Management System
// TODO: Replace all mock data with API calls to Convex backend

// ============ USERS ============
export const mockUsers = {
    organizers: [
        {
            _id: "org_001",
            name: "Prof. Rajesh Kumar",
            email: "rajesh.kumar@dypiu.ac.in",
            role: "organiser",
            department: "Computer Engineering",
            phone: "+91 98765 43210",
            imageUrl: null,
        },
        {
            _id: "org_002",
            name: "Dr. Sneha Patil",
            email: "sneha.patil@dypiu.ac.in",
            role: "organiser",
            department: "Information Technology",
            phone: "+91 98765 43211",
            imageUrl: null,
        },
    ],
    students: [
        {
            _id: "stu_001",
            name: "Aarav Sharma",
            email: "aarav.sharma@dypiu.ac.in",
            role: "student",
            studentId: "DYPIU2024001",
            department: "Computer Engineering",
            year: 3,
        },
        {
            _id: "stu_002",
            name: "Priya Deshmukh",
            email: "priya.deshmukh@dypiu.ac.in",
            role: "student",
            studentId: "DYPIU2024002",
            department: "Information Technology",
            year: 2,
        },
        {
            _id: "stu_003",
            name: "Rohan Joshi",
            email: "rohan.joshi@dypiu.ac.in",
            role: "student",
            studentId: "DYPIU2024003",
            department: "Electronics",
            year: 4,
        },
        {
            _id: "stu_004",
            name: "Ananya Kulkarni",
            email: "ananya.kulkarni@dypiu.ac.in",
            role: "student",
            studentId: "DYPIU2024004",
            department: "Mechanical Engineering",
            year: 2,
        },
        {
            _id: "stu_005",
            name: "Vikram Singh",
            email: "vikram.singh@dypiu.ac.in",
            role: "student",
            studentId: "DYPIU2024005",
            department: "Computer Engineering",
            year: 3,
        },
    ],
};

// ============ EVENTS ============
const now = Date.now();
const day = 24 * 60 * 60 * 1000;

export const mockUpcomingEvents = [
    {
        _id: "evt_u01",
        title: "TechFusion 2026 — Annual Hackathon",
        description:
            "A 36-hour hackathon bringing together the brightest minds to solve real-world challenges. Prizes worth ₹2,00,000!",
        organizerId: "org_001",
        organizerName: "Prof. Rajesh Kumar",
        category: "tech",
        tags: ["hackathon", "coding", "innovation"],
        startDate: now + 5 * day,
        endDate: now + 7 * day,
        timezone: "Asia/Kolkata",
        locationType: "physical",
        venue: "Main Auditorium",
        address: "D. Y. Patil International University, Pimpri",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 300,
        ticketType: "free",
        registrationCount: 187,
        coverImage: null,
        themeColor: "#1e40af",
        status: "upcoming",
        slug: "techfusion-2026",
        eventCode: "TF2026",
    },
    {
        _id: "evt_u02",
        title: "Cultural Fiesta — Rhythm & Blues",
        description:
            "An evening of music, dance, and drama performances by talented students across all departments.",
        organizerId: "org_002",
        organizerName: "Dr. Sneha Patil",
        category: "music",
        tags: ["culture", "music", "dance"],
        startDate: now + 10 * day,
        endDate: now + 10 * day,
        timezone: "Asia/Kolkata",
        locationType: "physical",
        venue: "Open Air Theatre",
        address: "DYPIU Campus",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 500,
        ticketType: "free",
        registrationCount: 342,
        coverImage: null,
        themeColor: "#9333ea",
        status: "upcoming",
        slug: "cultural-fiesta-2026",
        eventCode: "CF2026",
    },
    {
        _id: "evt_u03",
        title: "AI/ML Workshop — From Basics to Deployment",
        description:
            "Hands-on workshop covering machine learning fundamentals, model training, and deployment with real-world datasets.",
        organizerId: "org_001",
        organizerName: "Prof. Rajesh Kumar",
        category: "education",
        tags: ["AI", "machine learning", "workshop"],
        startDate: now + 3 * day,
        endDate: now + 3 * day,
        timezone: "Asia/Kolkata",
        locationType: "physical",
        venue: "Seminar Hall B",
        address: "DYPIU Campus",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 80,
        ticketType: "free",
        registrationCount: 72,
        coverImage: null,
        themeColor: "#059669",
        status: "upcoming",
        slug: "aiml-workshop-2026",
        eventCode: "AIML26",
    },
    {
        _id: "evt_u04",
        title: "Inter-Department Cricket Tournament",
        description:
            "Annual inter-department cricket tournament. Teams from all departments compete for the DYPIU Champions Trophy.",
        organizerId: "org_002",
        organizerName: "Dr. Sneha Patil",
        category: "sports",
        tags: ["cricket", "sports", "tournament"],
        startDate: now + 14 * day,
        endDate: now + 16 * day,
        timezone: "Asia/Kolkata",
        locationType: "physical",
        venue: "DYPIU Sports Ground",
        address: "DYPIU Campus",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 200,
        ticketType: "free",
        registrationCount: 156,
        coverImage: null,
        themeColor: "#ea580c",
        status: "upcoming",
        slug: "cricket-tournament-2026",
        eventCode: "CRKT26",
    },
    {
        _id: "evt_u05",
        title: "Startup Pitch Day",
        description:
            "Present your startup ideas to a panel of industry experts and investors. Top 3 ideas win incubation support!",
        organizerId: "org_001",
        organizerName: "Prof. Rajesh Kumar",
        category: "business",
        tags: ["startup", "entrepreneurship", "pitch"],
        startDate: now + 8 * day,
        endDate: now + 8 * day,
        timezone: "Asia/Kolkata",
        locationType: "physical",
        venue: "Conference Hall",
        address: "DYPIU Campus",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 100,
        ticketType: "free",
        registrationCount: 48,
        coverImage: null,
        themeColor: "#0891b2",
        status: "upcoming",
        slug: "startup-pitch-day-2026",
        eventCode: "SPD26",
    },
    {
        _id: "evt_u06",
        title: "Robotics Exhibition & Demo",
        description:
            "Showcase of student-built robots, drones, and automation projects. Live demonstrations and Q&A sessions.",
        organizerId: "org_002",
        organizerName: "Dr. Sneha Patil",
        category: "tech",
        tags: ["robotics", "innovation", "demo"],
        startDate: now + 12 * day,
        endDate: now + 12 * day,
        timezone: "Asia/Kolkata",
        locationType: "physical",
        venue: "Innovation Lab",
        address: "DYPIU Campus",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 150,
        ticketType: "free",
        registrationCount: 89,
        coverImage: null,
        themeColor: "#6d28d9",
        status: "upcoming",
        slug: "robotics-exhibition-2026",
        eventCode: "ROBO26",
    },
];

export const mockPastEvents = [
    {
        _id: "evt_p01",
        title: "Code Sprint 2025",
        description:
            "Competitive programming contest with 500+ participants from across Maharashtra.",
        organizerId: "org_001",
        organizerName: "Prof. Rajesh Kumar",
        category: "tech",
        tags: ["coding", "competition"],
        startDate: now - 60 * day,
        endDate: now - 59 * day,
        locationType: "physical",
        venue: "Computer Lab Complex",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 500,
        ticketType: "free",
        registrationCount: 478,
        attendeeCount: 412,
        coverImage: null,
        themeColor: "#1e40af",
        status: "completed",
        slug: "code-sprint-2025",
        eventCode: "CS2025",
    },
    {
        _id: "evt_p02",
        title: "Annual Sports Day 2025",
        description:
            "A full day of athletics, team sports, and individual competitions across the campus.",
        organizerId: "org_002",
        organizerName: "Dr. Sneha Patil",
        category: "sports",
        tags: ["sports", "athletics"],
        startDate: now - 45 * day,
        endDate: now - 45 * day,
        locationType: "physical",
        venue: "DYPIU Sports Complex",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 800,
        ticketType: "free",
        registrationCount: 650,
        attendeeCount: 580,
        coverImage: null,
        themeColor: "#ea580c",
        status: "completed",
        slug: "sports-day-2025",
        eventCode: "SD2025",
    },
    {
        _id: "evt_p03",
        title: "Guest Lecture — Future of Cloud Computing",
        description:
            "Industry expert session on cloud technologies, serverless architecture, and career opportunities.",
        organizerId: "org_001",
        organizerName: "Prof. Rajesh Kumar",
        category: "education",
        tags: ["cloud", "lecture", "technology"],
        startDate: now - 30 * day,
        endDate: now - 30 * day,
        locationType: "physical",
        venue: "Seminar Hall A",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 200,
        ticketType: "free",
        registrationCount: 185,
        attendeeCount: 160,
        coverImage: null,
        themeColor: "#059669",
        status: "completed",
        slug: "cloud-computing-lecture",
        eventCode: "CCL25",
    },
    {
        _id: "evt_p04",
        title: "Diwali Cultural Night",
        description:
            "Grand celebration featuring traditional dances, singing, and festive food stalls.",
        organizerId: "org_002",
        organizerName: "Dr. Sneha Patil",
        category: "art",
        tags: ["culture", "festival", "celebration"],
        startDate: now - 90 * day,
        endDate: now - 90 * day,
        locationType: "physical",
        venue: "Main Auditorium",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 600,
        ticketType: "free",
        registrationCount: 520,
        attendeeCount: 490,
        coverImage: null,
        themeColor: "#d97706",
        status: "completed",
        slug: "diwali-cultural-night",
        eventCode: "DCN25",
    },
    {
        _id: "evt_p05",
        title: "Web Development Bootcamp",
        description:
            "3-day intensive bootcamp covering React, Node.js, and database design with real project building.",
        organizerId: "org_001",
        organizerName: "Prof. Rajesh Kumar",
        category: "tech",
        tags: ["web", "workshop", "bootcamp"],
        startDate: now - 20 * day,
        endDate: now - 18 * day,
        locationType: "physical",
        venue: "Lab 201",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 60,
        ticketType: "free",
        registrationCount: 58,
        attendeeCount: 52,
        coverImage: null,
        themeColor: "#7c3aed",
        status: "completed",
        slug: "web-dev-bootcamp",
        eventCode: "WDB25",
    },
    {
        _id: "evt_p06",
        title: "Photography Exhibition",
        description:
            "Showcasing the best student photography across categories: nature, street, portrait, and abstract.",
        organizerId: "org_002",
        organizerName: "Dr. Sneha Patil",
        category: "art",
        tags: ["photography", "art", "exhibition"],
        startDate: now - 15 * day,
        endDate: now - 14 * day,
        locationType: "physical",
        venue: "Gallery Hall",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 150,
        ticketType: "free",
        registrationCount: 120,
        attendeeCount: 105,
        coverImage: null,
        themeColor: "#0284c7",
        status: "completed",
        slug: "photography-exhibition",
        eventCode: "PE2025",
    },
    {
        _id: "evt_p07",
        title: "Entrepreneurship Summit 2025",
        description:
            "Two-day summit featuring startup founders, investor panels, and networking sessions.",
        organizerId: "org_001",
        organizerName: "Prof. Rajesh Kumar",
        category: "business",
        tags: ["entrepreneurship", "startup", "networking"],
        startDate: now - 75 * day,
        endDate: now - 74 * day,
        locationType: "physical",
        venue: "Conference Center",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 250,
        ticketType: "free",
        registrationCount: 220,
        attendeeCount: 195,
        coverImage: null,
        themeColor: "#0891b2",
        status: "completed",
        slug: "entrepreneurship-summit-2025",
        eventCode: "ES2025",
    },
    {
        _id: "evt_p08",
        title: "Health & Wellness Week",
        description:
            "Week-long activities including yoga, meditation, health checkups, and nutrition workshops.",
        organizerId: "org_002",
        organizerName: "Dr. Sneha Patil",
        category: "health",
        tags: ["health", "wellness", "yoga"],
        startDate: now - 40 * day,
        endDate: now - 35 * day,
        locationType: "physical",
        venue: "Sports Complex",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        capacity: 400,
        ticketType: "free",
        registrationCount: 310,
        attendeeCount: 275,
        coverImage: null,
        themeColor: "#16a34a",
        status: "completed",
        slug: "health-wellness-week",
        eventCode: "HWW25",
    },
];

// ============ ATTENDANCE RECORDS ============
export const mockAttendanceRecords = [
    {
        _id: "att_001",
        eventId: "evt_p01",
        studentId: "stu_001",
        studentName: "Aarav Sharma",
        studentEmail: "aarav.sharma@dypiu.ac.in",
        department: "Computer Engineering",
        registeredAt: now - 65 * day,
        attendanceStatus: "attended",
        checkInTime: now - 60 * day + 2 * 60 * 60 * 1000,
        qrScanned: true,
        manualEntry: false,
    },
    {
        _id: "att_002",
        eventId: "evt_p01",
        studentId: "stu_002",
        studentName: "Priya Deshmukh",
        studentEmail: "priya.deshmukh@dypiu.ac.in",
        department: "Information Technology",
        registeredAt: now - 63 * day,
        attendanceStatus: "attended",
        checkInTime: now - 60 * day + 2.5 * 60 * 60 * 1000,
        qrScanned: false,
        manualEntry: true,
    },
    {
        _id: "att_003",
        eventId: "evt_p01",
        studentId: "stu_003",
        studentName: "Rohan Joshi",
        studentEmail: "rohan.joshi@dypiu.ac.in",
        department: "Electronics",
        registeredAt: now - 62 * day,
        attendanceStatus: "absent",
        checkInTime: null,
        qrScanned: false,
        manualEntry: false,
    },
    {
        _id: "att_004",
        eventId: "evt_u01",
        studentId: "stu_001",
        studentName: "Aarav Sharma",
        studentEmail: "aarav.sharma@dypiu.ac.in",
        department: "Computer Engineering",
        registeredAt: now - 2 * day,
        attendanceStatus: "registered",
        checkInTime: null,
        qrScanned: false,
        manualEntry: false,
    },
    {
        _id: "att_005",
        eventId: "evt_u01",
        studentId: "stu_004",
        studentName: "Ananya Kulkarni",
        studentEmail: "ananya.kulkarni@dypiu.ac.in",
        department: "Mechanical Engineering",
        registeredAt: now - 1 * day,
        attendanceStatus: "registered",
        checkInTime: null,
        qrScanned: false,
        manualEntry: false,
    },
    {
        _id: "att_006",
        eventId: "evt_u03",
        studentId: "stu_005",
        studentName: "Vikram Singh",
        studentEmail: "vikram.singh@dypiu.ac.in",
        department: "Computer Engineering",
        registeredAt: now - 1 * day,
        attendanceStatus: "registered",
        checkInTime: null,
        qrScanned: false,
        manualEntry: false,
    },
];

// ============ STATISTICS ============
export const mockStatistics = {
    totalEvents: 42,
    totalParticipants: 4850,
    totalDepartments: 8,
    totalOrganizers: 15,
    attendanceRate: 87,
    eventsThisMonth: 6,
};

// ============ CHART DATA FOR REPORTS ============
export const mockChartData = {
    attendanceOverTime: [
        { month: "Sep", attendees: 320 },
        { month: "Oct", attendees: 580 },
        { month: "Nov", attendees: 490 },
        { month: "Dec", attendees: 350 },
        { month: "Jan", attendees: 620 },
        { month: "Feb", attendees: 710 },
    ],
    eventWiseParticipation: [
        { event: "TechFusion", registered: 478, attended: 412 },
        { event: "Sports Day", registered: 650, attended: 580 },
        { event: "Cloud Talk", registered: 185, attended: 160 },
        { event: "Diwali Night", registered: 520, attended: 490 },
        { event: "Web Bootcamp", registered: 58, attended: 52 },
        { event: "Photo Expo", registered: 120, attended: 105 },
    ],
    categoryDistribution: [
        { name: "Technology", value: 14, fill: "#3b82f6" },
        { name: "Sports", value: 6, fill: "#ea580c" },
        { name: "Arts & Culture", value: 8, fill: "#9333ea" },
        { name: "Education", value: 7, fill: "#059669" },
        { name: "Business", value: 4, fill: "#0891b2" },
        { name: "Health", value: 3, fill: "#16a34a" },
    ],
    reportSummary: {
        totalEvents: 42,
        totalAttendees: 4850,
        averageAttendance: 115,
        attendanceRate: 87,
        mostPopularEvent: "Annual Sports Day 2025",
        mostPopularCategory: "Technology",
        totalHoursOfEvents: 180,
    },
};

// ============ EVENT CATEGORIES ============
export const eventCategories = [
    { value: "all", label: "All Categories" },
    { value: "tech", label: "Technology" },
    { value: "music", label: "Music" },
    { value: "sports", label: "Sports" },
    { value: "art", label: "Art & Culture" },
    { value: "education", label: "Education" },
    { value: "business", label: "Business" },
    { value: "health", label: "Health & Wellness" },
    { value: "gaming", label: "Gaming" },
    { value: "community", label: "Community" },
];
